const mongoose = require('mongoose');
const Exercise = require('../models/Exercise');

const SYSTEM_EXERCISES = [
  // CHEST (35 exercises)
  { name: "Bench Press", muscleGroup: "Chest", category: "Chest", equipment: "Barbell", description: "Flat barbell bench press for overall chest strength." },
  { name: "Incline Bench Press", muscleGroup: "Chest", category: "Chest", equipment: "Barbell", description: "Upper chest focused press on an inclined bench." },
  { name: "Decline Bench Press", muscleGroup: "Chest", category: "Chest", equipment: "Barbell", description: "Lower chest focused press on a declined bench." },
  { name: "Close Grip Bench Press", muscleGroup: "Chest", category: "Triceps", equipment: "Barbell", description: "Tricep and inner chest focused press." },
  { name: "Wide Grip Bench Press", muscleGroup: "Chest", category: "Chest", equipment: "Barbell", description: "Wide grip press emphasizing outer pectorals." },
  { name: "Paused Bench Press", muscleGroup: "Chest", category: "Chest", equipment: "Barbell", description: "Explosive chest press with a 2-second pause at chest." },
  { name: "Spoto Press", muscleGroup: "Chest", category: "Chest", equipment: "Barbell", description: "Bench press paused 1-2 inches above chest." },
  { name: "Floor Press", muscleGroup: "Chest", category: "Chest", equipment: "Barbell", description: "Barbell press lying on the floor limiting shoulder extension." },
  { name: "Dumbbell Bench Press", muscleGroup: "Chest", category: "Chest", equipment: "Dumbbell", description: "Flat dumbbell press allowing deep stretch." },
  { name: "Incline Dumbbell Press", muscleGroup: "Chest", category: "Chest", equipment: "Dumbbell", description: "Incline dumbbell press for upper chest development." },
  { name: "Decline Dumbbell Press", muscleGroup: "Chest", category: "Chest", equipment: "Dumbbell", description: "Decline dumbbell press targeting lower pectorals." },
  { name: "Dumbbell Fly", muscleGroup: "Chest", category: "Chest", equipment: "Dumbbell", description: "Flat dumbbell chest isolation fly movement." },
  { name: "Incline Dumbbell Fly", muscleGroup: "Chest", category: "Chest", equipment: "Dumbbell", description: "Upper chest dumbbell isolation fly." },
  { name: "Decline Dumbbell Fly", muscleGroup: "Chest", category: "Chest", equipment: "Dumbbell", description: "Lower chest dumbbell isolation fly." },
  { name: "Cable Crossover", muscleGroup: "Chest", category: "Chest", equipment: "Cable", description: "Mid-level cable crossover fly." },
  { name: "Low Cable Crossover", muscleGroup: "Chest", category: "Chest", equipment: "Cable", description: "Low to high cable fly targeting upper chest." },
  { name: "High Cable Crossover", muscleGroup: "Chest", category: "Chest", equipment: "Cable", description: "High to low cable fly targeting lower chest." },
  { name: "Cable Chest Fly", muscleGroup: "Chest", category: "Chest", equipment: "Cable", description: "Seated or standing cable chest fly." },
  { name: "Machine Chest Press", muscleGroup: "Chest", category: "Chest", equipment: "Machine", description: "Seated plate-loaded or pin-select chest press." },
  { name: "Incline Machine Press", muscleGroup: "Chest", category: "Chest", equipment: "Machine", description: "Upper chest machine press." },
  { name: "Decline Machine Press", muscleGroup: "Chest", category: "Chest", equipment: "Machine", description: "Lower chest machine press." },
  { name: "Pec Deck", muscleGroup: "Chest", category: "Chest", equipment: "Machine", description: "Butterfly machine chest fly." },
  { name: "Chest Dips", muscleGroup: "Chest", category: "Chest", equipment: "Bodyweight", description: "Bodyweight dips with forward torso lean." },
  { name: "Assisted Chest Dips", muscleGroup: "Chest", category: "Chest", equipment: "Machine", description: "Machine-assisted chest dips." },
  { name: "Weighted Chest Dips", muscleGroup: "Chest", category: "Chest", equipment: "Other", description: "Dips performed with added weight belt." },
  { name: "Push Up", muscleGroup: "Chest", category: "Chest", equipment: "Bodyweight", description: "Standard bodyweight push up." },
  { name: "Wide Push Up", muscleGroup: "Chest", category: "Chest", equipment: "Bodyweight", description: "Wide stance push up targeting outer chest." },
  { name: "Close Grip Push Up", muscleGroup: "Chest", category: "Triceps", equipment: "Bodyweight", description: "Narrow stance push up." },
  { name: "Decline Push Up", muscleGroup: "Chest", category: "Chest", equipment: "Bodyweight", description: "Feet elevated push up targeting upper chest." },
  { name: "Incline Push Up", muscleGroup: "Chest", category: "Chest", equipment: "Bodyweight", description: "Hands elevated push up." },
  { name: "Diamond Push Up", muscleGroup: "Chest", category: "Triceps", equipment: "Bodyweight", description: "Push up with hands touching in diamond shape." },
  { name: "Archer Push Up", muscleGroup: "Chest", category: "Chest", equipment: "Bodyweight", description: "Side-to-side bodyweight push up variation." },
  { name: "Weighted Push Up", muscleGroup: "Chest", category: "Chest", equipment: "Other", description: "Push up with plate on back." },
  { name: "Landmine Chest Press", muscleGroup: "Chest", category: "Chest", equipment: "Barbell", description: "Standing angled landmine chest press." },
  { name: "Svend Press", muscleGroup: "Chest", category: "Chest", equipment: "Dumbbell", description: "Standing plate squeeze press." },

  // BACK (40 exercises)
  { name: "Deadlift", muscleGroup: "Back", category: "Back", equipment: "Barbell", description: "Conventional barbell deadlift for total posterior chain." },
  { name: "Conventional Deadlift", muscleGroup: "Back", category: "Back", equipment: "Barbell", description: "Standard stance heavy pull." },
  { name: "Sumo Deadlift", muscleGroup: "Back", category: "Back", equipment: "Barbell", description: "Wide-stance sumo deadlift." },
  { name: "Romanian Deadlift", muscleGroup: "Back", category: "Hamstrings", equipment: "Barbell", description: "Hinge movement for hamstrings and lower back." },
  { name: "Stiff Leg Deadlift", muscleGroup: "Back", category: "Hamstrings", equipment: "Barbell", description: "Straight-leg pull from floor." },
  { name: "Trap Bar Deadlift", muscleGroup: "Back", category: "Back", equipment: "Trap Bar", description: "Hex bar deadlift with neutral grip." },
  { name: "Rack Pull", muscleGroup: "Back", category: "Back", equipment: "Barbell", description: "Partial deadlift pulled from knee height in power rack." },
  { name: "Barbell Row", muscleGroup: "Back", category: "Back", equipment: "Barbell", description: "Bent over barbell row." },
  { name: "Pendlay Row", muscleGroup: "Back", category: "Back", equipment: "Barbell", description: "Strict bent over row starting flat from floor each rep." },
  { name: "T-Bar Row", muscleGroup: "Back", category: "Back", equipment: "Barbell", description: "Angled landmine T-bar row." },
  { name: "Chest Supported Row", muscleGroup: "Back", category: "Back", equipment: "Machine", description: "Incline bench supported row eliminating lower back strain." },
  { name: "Dumbbell Row", muscleGroup: "Back", category: "Back", equipment: "Dumbbell", description: "Single-arm dumbbell row on bench." },
  { name: "One Arm Dumbbell Row", muscleGroup: "Back", category: "Back", equipment: "Dumbbell", description: "Classic single arm dumbbell pull." },
  { name: "Incline Dumbbell Row", muscleGroup: "Back", category: "Back", equipment: "Dumbbell", description: "Prone incline bench dumbbell row." },
  { name: "Seated Cable Row", muscleGroup: "Back", category: "Back", equipment: "Cable", description: "Seated horizontal cable row." },
  { name: "Close Grip Cable Row", muscleGroup: "Back", category: "Back", equipment: "Cable", description: "V-bar attachment cable row." },
  { name: "Wide Grip Cable Row", muscleGroup: "Back", category: "Back", equipment: "Cable", description: "Wide lat attachment cable row." },
  { name: "Single Arm Cable Row", muscleGroup: "Back", category: "Back", equipment: "Cable", description: "Unilateral standing cable row." },
  { name: "Machine Row", muscleGroup: "Back", category: "Back", equipment: "Machine", description: "Leverage machine rowing motion." },
  { name: "Lat Pulldown", muscleGroup: "Back", category: "Back", equipment: "Cable", description: "Standard vertical lat pulldown." },
  { name: "Wide Grip Lat Pulldown", muscleGroup: "Back", category: "Back", equipment: "Cable", description: "Wide grip pulldown for upper lats." },
  { name: "Close Grip Lat Pulldown", muscleGroup: "Back", category: "Back", equipment: "Cable", description: "Underhand or neutral close grip pulldown." },
  { name: "Reverse Grip Lat Pulldown", muscleGroup: "Back", category: "Back", equipment: "Cable", description: "Supinated grip pulldown." },
  { name: "Neutral Grip Lat Pulldown", muscleGroup: "Back", category: "Back", equipment: "Cable", description: "Parallel handles pulldown." },
  { name: "Single Arm Lat Pulldown", muscleGroup: "Back", category: "Back", equipment: "Cable", description: "Unilateral cable pulldown." },
  { name: "Pull Up", muscleGroup: "Back", category: "Back", equipment: "Bodyweight", description: "Overhand bodyweight pull up." },
  { name: "Wide Grip Pull Up", muscleGroup: "Back", category: "Back", equipment: "Bodyweight", description: "Wide overhand grip pull up." },
  { name: "Close Grip Pull Up", muscleGroup: "Back", category: "Back", equipment: "Bodyweight", description: "Narrow grip pull up." },
  { name: "Chin Up", muscleGroup: "Back", category: "Back", equipment: "Bodyweight", description: "Underhand bodyweight chin up." },
  { name: "Neutral Grip Pull Up", muscleGroup: "Back", category: "Back", equipment: "Bodyweight", description: "Palms facing pull up." },
  { name: "Assisted Pull Up", muscleGroup: "Back", category: "Back", equipment: "Machine", description: "Counterbalanced machine pull up." },
  { name: "Weighted Pull Up", muscleGroup: "Back", category: "Back", equipment: "Other", description: "Pull up with dip belt weight." },
  { name: "Straight Arm Pulldown", muscleGroup: "Back", category: "Back", equipment: "Cable", description: "Standing cable lat pushdown." },
  { name: "Dumbbell Pullover", muscleGroup: "Back", category: "Back", equipment: "Dumbbell", description: "Cross-bench dumbbell pullover." },
  { name: "Cable Pullover", muscleGroup: "Back", category: "Back", equipment: "Cable", description: "Bench standing cable pullover." },
  { name: "Machine Pullover", muscleGroup: "Back", category: "Back", equipment: "Machine", description: "Nautilus style machine lat pullover." },
  { name: "Inverted Row", muscleGroup: "Back", category: "Back", equipment: "Bodyweight", description: "Smith machine or suspension body weight row." },
  { name: "Face Pull", muscleGroup: "Back", category: "Shoulders", equipment: "Cable", description: "Rope attachment face pull for rear delts and upper back." },
  { name: "Meadows Row", muscleGroup: "Back", category: "Back", equipment: "Barbell", description: "Single-arm landmine row popularized by John Meadows." },
  { name: "Hyperextension", muscleGroup: "Back", category: "Back", equipment: "Bodyweight", description: "45-degree lower back extension." },

  // SHOULDERS (30 exercises)
  { name: "Overhead Press", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Barbell", description: "Standing strict barbell shoulder press." },
  { name: "Barbell Overhead Press", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Barbell", description: "Military press standing." },
  { name: "Seated Barbell Press", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Barbell", description: "Seated military shoulder press." },
  { name: "Dumbbell Shoulder Press", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Dumbbell", description: "Seated dumbbell overhead press." },
  { name: "Seated Dumbbell Press", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Dumbbell", description: "Vertical dumbbell shoulder press." },
  { name: "Arnold Press", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Dumbbell", description: "Rotating dumbbell shoulder press." },
  { name: "Machine Shoulder Press", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Machine", description: "Plate loaded overhead shoulder press." },
  { name: "Smith Machine Shoulder Press", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Smith Machine", description: "Guided bar shoulder press." },
  { name: "Push Press", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Barbell", description: "Leg-assisted explosive overhead press." },
  { name: "Landmine Press", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Barbell", description: "Angled landmine shoulder press." },
  { name: "Single Arm Landmine Press", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Barbell", description: "Unilateral landmine press." },
  { name: "Lateral Raise", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Dumbbell", description: "Side lateral raise for side delts." },
  { name: "Dumbbell Lateral Raise", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Dumbbell", description: "Standing dumbbell side raise." },
  { name: "Cable Lateral Raise", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Cable", description: "Low cable side lateral raise." },
  { name: "Machine Lateral Raise", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Machine", description: "Seated lateral raise machine." },
  { name: "Lean Away Lateral Raise", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Cable", description: "Single-arm cable raise leaning away from pole." },
  { name: "Front Raise", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Dumbbell", description: "Front delt raises." },
  { name: "Dumbbell Front Raise", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Dumbbell", description: "Alternating dumbbell front raise." },
  { name: "Cable Front Raise", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Cable", description: "Low cable front raise." },
  { name: "Plate Front Raise", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Other", description: "Weight plate front raise." },
  { name: "Rear Delt Fly", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Dumbbell", description: "Bent over rear delt fly." },
  { name: "Reverse Pec Deck", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Machine", description: "Machine rear delt fly." },
  { name: "Cable Rear Delt Fly", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Cable", description: "Crossed cable rear delt fly." },
  { name: "Bent Over Dumbbell Raise", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Dumbbell", description: "Prone incline or bent over rear delt raise." },
  { name: "Upright Row", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Barbell", description: "Barbell upright row to chest." },
  { name: "Barbell Upright Row", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Barbell", description: "Standing barbell upright row." },
  { name: "Cable Upright Row", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Cable", description: "Cable attachment upright row." },
  { name: "Shrugs", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Dumbbell", description: "Trapezius elevation shrugs." },
  { name: "Barbell Shrug", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Barbell", description: "Heavy barbell shrug." },
  { name: "Dumbbell Shrug", muscleGroup: "Shoulders", category: "Shoulders", equipment: "Dumbbell", description: "Heavy dumbbell shrug." },

  // BICEPS (25 exercises)
  { name: "Barbell Curl", muscleGroup: "Arms", category: "Biceps", equipment: "Barbell", description: "Standing straight barbell bicep curl." },
  { name: "EZ Bar Curl", muscleGroup: "Arms", category: "Biceps", equipment: "EZ Bar", description: "Angled EZ bar bicep curl." },
  { name: "Dumbbell Curl", muscleGroup: "Arms", category: "Biceps", equipment: "Dumbbell", description: "Standing bicep curl with dumbbells." },
  { name: "Alternating Dumbbell Curl", muscleGroup: "Arms", category: "Biceps", equipment: "Dumbbell", description: "Alternating arms dumbbell curl with wrist supination." },
  { name: "Hammer Curl", muscleGroup: "Arms", category: "Biceps", equipment: "Dumbbell", description: "Neutral grip dumbbell curl targeting brachialis." },
  { name: "Cross Body Hammer Curl", muscleGroup: "Arms", category: "Biceps", equipment: "Dumbbell", description: "Hammer curl across chest." },
  { name: "Incline Dumbbell Curl", muscleGroup: "Arms", category: "Biceps", equipment: "Dumbbell", description: "Seated incline bench bicep curl for long head stretch." },
  { name: "Preacher Curl", muscleGroup: "Arms", category: "Biceps", equipment: "EZ Bar", description: "Preacher bench isolated bicep curl." },
  { name: "EZ Bar Preacher Curl", muscleGroup: "Arms", category: "Biceps", equipment: "EZ Bar", description: "EZ bar preacher bench curl." },
  { name: "Dumbbell Preacher Curl", muscleGroup: "Arms", category: "Biceps", equipment: "Dumbbell", description: "Single-arm dumbbell preacher curl." },
  { name: "Concentration Curl", muscleGroup: "Arms", category: "Biceps", equipment: "Dumbbell", description: "Seated leg-braced single arm dumbbell curl." },
  { name: "Spider Curl", muscleGroup: "Arms", category: "Biceps", equipment: "Barbell", description: "Prone incline bench preacher curl." },
  { name: "Cable Curl", muscleGroup: "Arms", category: "Biceps", equipment: "Cable", description: "Low pulley cable bicep curl." },
  { name: "Low Cable Curl", muscleGroup: "Arms", category: "Biceps", equipment: "Cable", description: "Straight bar low cable curl." },
  { name: "High Cable Curl", muscleGroup: "Arms", category: "Biceps", equipment: "Cable", description: "Dual cable arm curls at head height." },
  { name: "Bayesian Curl", muscleGroup: "Arms", category: "Biceps", equipment: "Cable", description: "Cable curl facing away from stack." },
  { name: "Machine Curl", muscleGroup: "Arms", category: "Biceps", equipment: "Machine", description: "Seated pin-select bicep curl machine." },
  { name: "Reverse Curl", muscleGroup: "Arms", category: "Forearms", equipment: "Barbell", description: "Overhand grip curl for brachioradialis." },
  { name: "Drag Curl", muscleGroup: "Arms", category: "Biceps", equipment: "Barbell", description: "Barbell curl dragging bar along torso." },
  { name: "21s", muscleGroup: "Arms", category: "Biceps", equipment: "Barbell", description: "7 bottom half, 7 top half, 7 full range reps." },
  { name: "Zottman Curl", muscleGroup: "Arms", category: "Biceps", equipment: "Dumbbell", description: "Curl up palms up, rotate, lower palms down." },
  { name: "Cable Hammer Curl", muscleGroup: "Arms", category: "Biceps", equipment: "Cable", description: "Rope attachment low cable hammer curl." },

  // TRICEPS (25 exercises)
  { name: "Tricep Pushdown", muscleGroup: "Arms", category: "Triceps", equipment: "Cable", description: "Cable stack tricep pushdown." },
  { name: "Rope Pushdown", muscleGroup: "Arms", category: "Triceps", equipment: "Cable", description: "Rope attachment cable tricep extension." },
  { name: "Straight Bar Pushdown", muscleGroup: "Arms", category: "Triceps", equipment: "Cable", description: "Straight bar tricep extension." },
  { name: "V Bar Pushdown", muscleGroup: "Arms", category: "Triceps", equipment: "Cable", description: "V-bar attachment cable pushdown." },
  { name: "Single Arm Pushdown", muscleGroup: "Arms", category: "Triceps", equipment: "Cable", description: "Unilateral reverse or overhand cable pushdown." },
  { name: "Overhead Tricep Extension", muscleGroup: "Arms", category: "Triceps", equipment: "Dumbbell", description: "Seated single or double hand overhead extension." },
  { name: "Dumbbell Overhead Extension", muscleGroup: "Arms", category: "Triceps", equipment: "Dumbbell", description: "Two-handed heavy dumbbell extension overhead." },
  { name: "Cable Overhead Extension", muscleGroup: "Arms", category: "Triceps", equipment: "Cable", description: "Low cable rope extension overhead." },
  { name: "EZ Bar Skull Crusher", muscleGroup: "Arms", category: "Triceps", equipment: "EZ Bar", description: "Lying tricep extension with EZ bar." },
  { name: "Barbell Skull Crusher", muscleGroup: "Arms", category: "Triceps", equipment: "Barbell", description: "Flat bench barbell skull crusher." },
  { name: "Dumbbell Skull Crusher", muscleGroup: "Arms", category: "Triceps", equipment: "Dumbbell", description: "Lying dumbbell tricep extension." },
  { name: "Tricep Dips", muscleGroup: "Arms", category: "Triceps", equipment: "Bodyweight", description: "Vertical torso bodyweight dips." },
  { name: "Bench Dips", muscleGroup: "Arms", category: "Triceps", equipment: "Bodyweight", description: "Bodyweight dips off flat bench." },
  { name: "Weighted Dips", muscleGroup: "Arms", category: "Triceps", equipment: "Other", description: "Heavy dips with weight belt." },
  { name: "Cable Kickback", muscleGroup: "Arms", category: "Triceps", equipment: "Cable", description: "Low cable single arm tricep kickback." },
  { name: "Dumbbell Kickback", muscleGroup: "Arms", category: "Triceps", equipment: "Dumbbell", description: "Bent-over dumbbell tricep extension." },
  { name: "Machine Tricep Extension", muscleGroup: "Arms", category: "Triceps", equipment: "Machine", description: "Seated pin-select tricep machine." },
  { name: "JM Press", muscleGroup: "Arms", category: "Triceps", equipment: "Barbell", description: "Hybrid bench press and skull crusher powerlifting exercise." },
  { name: "Tate Press", muscleGroup: "Arms", category: "Triceps", equipment: "Dumbbell", description: "Flat bench dumbbell press with elbows flared." },
  { name: "Rolling Dumbbell Extension", muscleGroup: "Arms", category: "Triceps", equipment: "Dumbbell", description: "Lying dumbbell extension with shoulder momentum transition." },

  // FOREARMS (10 exercises)
  { name: "Wrist Curl", muscleGroup: "Arms", category: "Forearms", equipment: "Barbell", description: "Seated barbell wrist flexor curl." },
  { name: "Reverse Wrist Curl", muscleGroup: "Arms", category: "Forearms", equipment: "Barbell", description: "Seated wrist extensor curl." },
  { name: "Barbell Wrist Curl", muscleGroup: "Arms", category: "Forearms", equipment: "Barbell", description: "Underhand forearm wrist flexion." },
  { name: "Dumbbell Wrist Curl", muscleGroup: "Arms", category: "Forearms", equipment: "Dumbbell", description: "Single-arm forearm wrist curl." },
  { name: "Behind Back Wrist Curl", muscleGroup: "Arms", category: "Forearms", equipment: "Barbell", description: "Standing barbell wrist curl behind glutes." },
  { name: "Reverse Barbell Curl", muscleGroup: "Arms", category: "Forearms", equipment: "Barbell", description: "Overhand grip forearm barbell curl." },
  { name: "Farmer's Walk", muscleGroup: "Full Body", category: "Forearms", equipment: "Dumbbell", description: "Heavy dumbbell or trap bar carry for grip strength." },
  { name: "Plate Pinch", muscleGroup: "Arms", category: "Forearms", equipment: "Other", description: "Isometric grip hold pinching weight plates." },
  { name: "Dead Hang", muscleGroup: "Back", category: "Forearms", equipment: "Bodyweight", description: "Timed pull-up bar hang for grip stamina." },

  // LEGS / QUADS (30 exercises)
  { name: "Barbell Squat", muscleGroup: "Legs", category: "Quads", equipment: "Barbell", description: "Classic back squat for quad strength." },
  { name: "Back Squat", muscleGroup: "Legs", category: "Quads", equipment: "Barbell", description: "High or low bar back squat." },
  { name: "Front Squat", muscleGroup: "Legs", category: "Quads", equipment: "Barbell", description: "Clean grip or crossed arm front rack squat." },
  { name: "High Bar Squat", muscleGroup: "Legs", category: "Quads", equipment: "Barbell", description: "Olympic style deep squat." },
  { name: "Low Bar Squat", muscleGroup: "Legs", category: "Quads", equipment: "Barbell", description: "Powerlifting squat focusing on hip drive." },
  { name: "Box Squat", muscleGroup: "Legs", category: "Quads", equipment: "Barbell", description: "Squat sitting onto plyo box." },
  { name: "Pause Squat", muscleGroup: "Legs", category: "Quads", equipment: "Barbell", description: "Squat with 2-second pause in the hole." },
  { name: "Hack Squat", muscleGroup: "Legs", category: "Quads", equipment: "Machine", description: "Angled hack squat machine." },
  { name: "Smith Machine Squat", muscleGroup: "Legs", category: "Quads", equipment: "Smith Machine", description: "Guided track squat." },
  { name: "Goblet Squat", muscleGroup: "Legs", category: "Quads", equipment: "Dumbbell", description: "Kettlebell or dumbbell held at chest squat." },
  { name: "Dumbbell Squat", muscleGroup: "Legs", category: "Quads", equipment: "Dumbbell", description: "Squat holding dumbbells at sides." },
  { name: "Belt Squat", muscleGroup: "Legs", category: "Quads", equipment: "Machine", description: "Machine squat loaded through waist belt." },
  { name: "Leg Press", muscleGroup: "Legs", category: "Quads", equipment: "Machine", description: "Heavy angled leg press machine." },
  { name: "45 Degree Leg Press", muscleGroup: "Legs", category: "Quads", equipment: "Machine", description: "Standard 45 degree sled press." },
  { name: "Horizontal Leg Press", muscleGroup: "Legs", category: "Quads", equipment: "Machine", description: "Pin-selected horizontal seated press." },
  { name: "Single Leg Press", muscleGroup: "Legs", category: "Quads", equipment: "Machine", description: "Unilateral 45 degree leg press." },
  { name: "Leg Extension", muscleGroup: "Legs", category: "Quads", equipment: "Machine", description: "Seated quad extension machine." },
  { name: "Single Leg Extension", muscleGroup: "Legs", category: "Quads", equipment: "Machine", description: "Unilateral leg extension." },
  { name: "Bulgarian Split Squat", muscleGroup: "Legs", category: "Quads", equipment: "Dumbbell", description: "Rear foot elevated single leg split squat." },
  { name: "Walking Lunge", muscleGroup: "Legs", category: "Quads", equipment: "Dumbbell", description: "Forward walking lunges." },
  { name: "Reverse Lunge", muscleGroup: "Legs", category: "Quads", equipment: "Dumbbell", description: "Stepping backward lunge." },
  { name: "Forward Lunge", muscleGroup: "Legs", category: "Quads", equipment: "Dumbbell", description: "Stationary forward lunge." },
  { name: "Barbell Lunge", muscleGroup: "Legs", category: "Quads", equipment: "Barbell", description: "Lunges with barbell across upper back." },
  { name: "Step Up", muscleGroup: "Legs", category: "Quads", equipment: "Dumbbell", description: "Stepping onto box or bench." },
  { name: "Sissy Squat", muscleGroup: "Legs", category: "Quads", equipment: "Bodyweight", description: "Bodyweight extreme quad isolation squat." },
  { name: "Cyclist Squat", muscleGroup: "Legs", category: "Quads", equipment: "Dumbbell", description: "Heels elevated narrow stance squat." },

  // HAMSTRINGS & GLUTES (25 exercises)
  { name: "Good Morning", muscleGroup: "Legs", category: "Hamstrings", equipment: "Barbell", description: "Barbell hip hinge for hamstrings and lower back." },
  { name: "Barbell Hip Thrust", muscleGroup: "Legs", category: "Glutes", equipment: "Barbell", description: "Upper back on bench heavy hip thrust." },
  { name: "Dumbbell Hip Thrust", muscleGroup: "Legs", category: "Glutes", equipment: "Dumbbell", description: "Hip thrust with dumbbell across hips." },
  { name: "Machine Hip Thrust", muscleGroup: "Legs", category: "Glutes", equipment: "Machine", description: "Dedicated glute drive machine." },
  { name: "Glute Bridge", muscleGroup: "Legs", category: "Glutes", equipment: "Bodyweight", description: "Floor glute bridge." },
  { name: "Single Leg Glute Bridge", muscleGroup: "Legs", category: "Glutes", equipment: "Bodyweight", description: "Unilateral floor glute extension." },
  { name: "Cable Pull Through", muscleGroup: "Legs", category: "Glutes", equipment: "Cable", description: "Low rope cable hip hinge pull through." },
  { name: "Leg Curl", muscleGroup: "Legs", category: "Hamstrings", equipment: "Machine", description: "Seated or lying leg curl machine." },
  { name: "Lying Leg Curl", muscleGroup: "Legs", category: "Hamstrings", equipment: "Machine", description: "Prone hamstring curl." },
  { name: "Seated Leg Curl", muscleGroup: "Legs", category: "Hamstrings", equipment: "Machine", description: "Seated hamstring curl machine." },
  { name: "Standing Leg Curl", muscleGroup: "Legs", category: "Hamstrings", equipment: "Machine", description: "Single leg standing leg curl." },
  { name: "Nordic Hamstring Curl", muscleGroup: "Legs", category: "Hamstrings", equipment: "Bodyweight", description: "Eccentric bodyweight hamstring lower." },
  { name: "Glute Ham Raise", muscleGroup: "Legs", category: "Hamstrings", equipment: "Bodyweight", description: "GHD bench bodyweight hamstring curl." },
  { name: "Reverse Hyperextension", muscleGroup: "Legs", category: "Glutes", equipment: "Machine", description: "Reverse hyper machine for glutes and lower back." },
  { name: "Glute Machine Kickback", muscleGroup: "Legs", category: "Glutes", equipment: "Machine", description: "Standing glute kickback machine." },
  { name: "Hip Abduction", muscleGroup: "Legs", category: "Glutes", equipment: "Machine", description: "Seated outer thigh/glute abduction." },
  { name: "Hip Adduction", muscleGroup: "Legs", category: "Quads", equipment: "Machine", description: "Seated inner thigh adduction." },

  // CALVES (10 exercises)
  { name: "Standing Calf Raise", muscleGroup: "Legs", category: "Calves", equipment: "Machine", description: "Heavy standing machine calf raise." },
  { name: "Seated Calf Raise", muscleGroup: "Legs", category: "Calves", equipment: "Machine", description: "Seated plate-loaded calf raise for soleus." },
  { name: "Leg Press Calf Raise", muscleGroup: "Legs", category: "Calves", equipment: "Machine", description: "Ankle extension on 45-degree leg press." },
  { name: "Donkey Calf Raise", muscleGroup: "Legs", category: "Calves", equipment: "Machine", description: "Bent-over hip-loaded calf raise." },
  { name: "Single Leg Calf Raise", muscleGroup: "Legs", category: "Calves", equipment: "Dumbbell", description: "Single-leg bodyweight or dumbbell calf extension." },
  { name: "Smith Machine Calf Raise", muscleGroup: "Legs", category: "Calves", equipment: "Smith Machine", description: "Standing calf extension on block under Smith bar." },
  { name: "Bodyweight Calf Raise", muscleGroup: "Legs", category: "Calves", equipment: "Bodyweight", description: "High rep floor calf raise." },

  // ABS & CORE (30 exercises)
  { name: "Crunch", muscleGroup: "Abs", category: "Abs", equipment: "Bodyweight", description: "Standard floor abdominal crunch." },
  { name: "Cable Crunch", muscleGroup: "Abs", category: "Abs", equipment: "Cable", description: "Kneeling high pulley rope cable crunch." },
  { name: "Machine Crunch", muscleGroup: "Abs", category: "Abs", equipment: "Machine", description: "Seated machine abdominal crunch." },
  { name: "Weighted Crunch", muscleGroup: "Abs", category: "Abs", equipment: "Other", description: "Floor crunch holding weight plate." },
  { name: "Decline Crunch", muscleGroup: "Abs", category: "Abs", equipment: "Bodyweight", description: "Decline bench crunch." },
  { name: "Sit Up", muscleGroup: "Abs", category: "Abs", equipment: "Bodyweight", description: "Full range sit up." },
  { name: "Weighted Sit Up", muscleGroup: "Abs", category: "Abs", equipment: "Other", description: "Sit up holding plate on chest." },
  { name: "Leg Raise", muscleGroup: "Abs", category: "Abs", equipment: "Bodyweight", description: "Flat bench or floor leg raise." },
  { name: "Hanging Leg Raise", muscleGroup: "Abs", category: "Abs", equipment: "Bodyweight", description: "Pull up bar hanging straight leg raise." },
  { name: "Captain's Chair Leg Raise", muscleGroup: "Abs", category: "Abs", equipment: "Bodyweight", description: "Tower apparatus vertical leg raise." },
  { name: "Hanging Knee Raise", muscleGroup: "Abs", category: "Abs", equipment: "Bodyweight", description: "Hanging knee tucks." },
  { name: "Reverse Crunch", muscleGroup: "Abs", category: "Abs", equipment: "Bodyweight", description: "Lying pelvis tilt crunch." },
  { name: "Bicycle Crunch", muscleGroup: "Abs", category: "Abs", equipment: "Bodyweight", description: "Alternating elbow to knee abdominal rotation." },
  { name: "Russian Twist", muscleGroup: "Abs", category: "Abs", equipment: "Bodyweight", description: "Seated torso twist." },
  { name: "Weighted Russian Twist", muscleGroup: "Abs", category: "Abs", equipment: "Dumbbell", description: "Russian twist holding medicine ball or dumbbell." },
  { name: "Plank", muscleGroup: "Abs", category: "Abs", equipment: "Bodyweight", description: "Isometric forearm floor plank." },
  { name: "Weighted Plank", muscleGroup: "Abs", category: "Abs", equipment: "Other", description: "Plank with plate on back." },
  { name: "Side Plank", muscleGroup: "Abs", category: "Abs", equipment: "Bodyweight", description: "Unilateral obliques plank." },
  { name: "Ab Wheel Rollout", muscleGroup: "Abs", category: "Abs", equipment: "Other", description: "Kneeling ab wheel rollout." },
  { name: "Mountain Climber", muscleGroup: "Abs", category: "Abs", equipment: "Bodyweight", description: "Dynamic push-up position knee drives." },
  { name: "Dead Bug", muscleGroup: "Abs", category: "Abs", equipment: "Bodyweight", description: "Lying arm and leg cross-coordination core control." },
  { name: "Pallof Press", muscleGroup: "Abs", category: "Abs", equipment: "Cable", description: "Anti-rotation cable press." },
  { name: "Cable Woodchop", muscleGroup: "Abs", category: "Abs", equipment: "Cable", description: "Diagonal cable rotational pull." },
  { name: "Landmine Rotation", muscleGroup: "Abs", category: "Abs", equipment: "Barbell", description: "Standing arc rotation with landmine bar." },
  { name: "Flutter Kicks", muscleGroup: "Abs", category: "Abs", equipment: "Bodyweight", description: "Lying lower abs flutter kicks." },
  { name: "Toe Touches", muscleGroup: "Abs", category: "Abs", equipment: "Bodyweight", description: "Lying vertical leg toe touch crunch." },

  // FULL BODY & FUNCTIONAL (20 exercises)
  { name: "Clean", muscleGroup: "Full Body", category: "Full Body", equipment: "Barbell", description: "Olympic barbell clean." },
  { name: "Power Clean", muscleGroup: "Full Body", category: "Full Body", equipment: "Barbell", description: "Explosive power clean from floor to shoulders." },
  { name: "Hang Clean", muscleGroup: "Full Body", category: "Full Body", equipment: "Barbell", description: "Clean pull initiating from above knees." },
  { name: "Clean and Press", muscleGroup: "Full Body", category: "Full Body", equipment: "Barbell", description: "Clean from floor into overhead press." },
  { name: "Snatch", muscleGroup: "Full Body", category: "Full Body", equipment: "Barbell", description: "Full Olympic snatch from floor overhead." },
  { name: "Power Snatch", muscleGroup: "Full Body", category: "Full Body", equipment: "Barbell", description: "Wide grip explosive snatch." },
  { name: "Kettlebell Swing", muscleGroup: "Full Body", category: "Full Body", equipment: "Kettlebell", description: "Russian hip hinge kettlebell swing." },
  { name: "Kettlebell Clean", muscleGroup: "Full Body", category: "Full Body", equipment: "Kettlebell", description: "Single or double kettlebell clean." },
  { name: "Kettlebell Press", muscleGroup: "Full Body", category: "Full Body", equipment: "Kettlebell", description: "Overhead kettlebell press." },
  { name: "Turkish Get Up", muscleGroup: "Full Body", category: "Full Body", equipment: "Kettlebell", description: "Lying to standing full body kettlebell control." },
  { name: "Suitcase Carry", muscleGroup: "Full Body", category: "Full Body", equipment: "Dumbbell", description: "Unilateral heavy walk." },
  { name: "Sled Push", muscleGroup: "Full Body", category: "Full Body", equipment: "Other", description: "Prowler weighted sled push sprint." },
  { name: "Sled Pull", muscleGroup: "Full Body", category: "Full Body", equipment: "Other", description: "Backward or rope sled pull." },
  { name: "Battle Rope", muscleGroup: "Full Body", category: "Full Body", equipment: "Other", description: "High intensity conditioning rope slams." },
  { name: "Medicine Ball Slam", muscleGroup: "Full Body", category: "Full Body", equipment: "Other", description: "Overhead slam onto floor." },
  { name: "Burpee", muscleGroup: "Full Body", category: "Full Body", equipment: "Bodyweight", description: "Full body push-up to jump burpee." },
  { name: "Box Jump", muscleGroup: "Full Body", category: "Full Body", equipment: "Bodyweight", description: "Explosive vertical jump onto plyo box." },
  { name: "Jump Squat", muscleGroup: "Full Body", category: "Full Body", equipment: "Bodyweight", description: "Bodyweight plyometric jump squat." },

  // CARDIO (15 exercises)
  { name: "Treadmill Running", muscleGroup: "Cardio", category: "Cardio", equipment: "Machine", description: "Treadmill running session." },
  { name: "Incline Treadmill Walk", muscleGroup: "Cardio", category: "Cardio", equipment: "Machine", description: "High incline low impact treadmill walking." },
  { name: "Stationary Bike", muscleGroup: "Cardio", category: "Cardio", equipment: "Machine", description: "Upright or recumbent cycling." },
  { name: "Elliptical", muscleGroup: "Cardio", category: "Cardio", equipment: "Machine", description: "Low impact elliptical cross-trainer." },
  { name: "Rowing Machine", muscleGroup: "Cardio", category: "Cardio", equipment: "Machine", description: "Ergometer indoor rowing." },
  { name: "Stairmaster", muscleGroup: "Cardio", category: "Cardio", equipment: "Machine", description: "Continuous stair climbing machine." },
  { name: "Jump Rope", muscleGroup: "Cardio", category: "Cardio", equipment: "Other", description: "Speed rope skipping." },
  { name: "Outdoor Jogging", muscleGroup: "Cardio", category: "Cardio", equipment: "Bodyweight", description: "Outdoor distance running." },
  { name: "Swimming", muscleGroup: "Cardio", category: "Cardio", equipment: "Bodyweight", description: "Full body swimming laps." }
];

const seedSystemExercises = async () => {
  try {
    const existingCount = await Exercise.countDocuments();
    console.log(`[Exercise Seeder] Current exercise count in DB: ${existingCount}`);

    // If exercises count is low, upsert missing master exercises safely without deleting user records
    if (existingCount < SYSTEM_EXERCISES.length) {
      console.log(`[Exercise Seeder] Seeding ${SYSTEM_EXERCISES.length} system master exercises...`);
      
      let inserted = 0;
      for (const ex of SYSTEM_EXERCISES) {
        const result = await Exercise.updateOne(
          { name: { $regex: new RegExp(`^${ex.name.trim()}$`, 'i') } },
          { $setOnInsert: ex },
          { upsert: true }
        );
        if (result.upsertedCount > 0) {
          inserted++;
        }
      }
      console.log(`[Exercise Seeder] Seeding complete! Successfully added ${inserted} new system exercises.`);
    } else {
      console.log(`[Exercise Seeder] System exercise library is fully populated (${existingCount} exercises). Skipping.`);
    }
  } catch (err) {
    console.error('[Exercise Seeder] Error during exercise seeding:', err.message);
  }
};

module.exports = { SYSTEM_EXERCISES, seedSystemExercises };
